[package]
name = "alco"
version = "0.1.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[features]
default = ["neovim", "tmux"]
neovim = ["async-std", "nvim-rs"]
tmux = []

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
humantime = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
shellexpand = "2.1.0"
yaml-rust = "0.4.5"

async-std = { version = "1.9", optional = true }
nvim-rs = { version = "0.2.0", features = ["use_async-std"], optional = true }
