[package]
name = "alacritty-colorscheme"
version = "0.1.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
directories-next = "2.0"
clap = "3.0.0-beta.2"
serde_yaml = "0.8"
serde = { version = "1.0", features = ["derive"] }
yaml-rust = "0.4.5"
humantime = "2.1"
