[package]
name = "alco"
version = "0.1.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[features]
default = ["neovim", "tmux", "delta", "cmus"]
neovim = ["nvim-rs"]
tmux = []
delta = []
cmus = []

[dependencies]
anyhow = "1.0"
async-std = "1.10"
clap = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.4"
humantime = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
shellexpand = "2.1.0"
yaml-rust = "0.4.5"

nvim-rs = { version = "0.3.1", features = ["use_async-std"], optional = true }
