[package]
name = "alco"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[features]
default = ["alacritty", "kitty", "tmux", "neovim", "delta", "cmus"]
alacritty = []
kitty = []
tmux = []
neovim = ["nvim-rs"]
delta = []
cmus = []

[dependencies]
anyhow = "1.0"
async-std = "1.10"
clap = { version = "=3.0.0-rc.0", features = ["cargo"] }
clap_generate = "=3.0.0-rc.0"
humantime = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
shellexpand = "2.1.0"
yaml-rust = "0.4.5"

nvim-rs = { version = "0.3.1", features = ["use_async-std"], optional = true }
